spring.application.name=task-manager-project

spring.datasource.url=URL_BASE_DADOS
spring.datasource.username=USUARIO_BASE_DADOS
spring.datasource.password=SENHA_BASE_DADOS

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=SUA_CHAVE_SECRETA
jwt.expiration=TEMPO_EXPIRACAO_CHAVE_SECRETA